name: PlatformRunner
version: 0.1.0.0
github: jtnuttall/PlatformRunner
license: GPL-2
author: Jeremy Nuttall
maintainer: jeremy@jeremy-nuttall.com
copyright: 2021 Jeremy Nuttall

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
synopsis: Simple platformer
category: Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on Github at <https://github.com/jtnuttall/PlatformRunner#readme>

dependencies:
  - base >= 4.11 && < 10
  - rio >= 0.1.12.0
  - linear
  - gloss
  - microlens-platform

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - TypeApplications
  - ViewPatterns

library:
  source-dirs: src
  dependencies:
    - apecs
    - apecs-physics
    - apecs-gloss
    - splitmix
    - template-haskell
    - conduit
    - async
    - stm
    - stm-chans
    - aeson
    - yaml
    - yamlparse-applicative
    - lens
  # ghc-options:
  # - -O2

executables:
  PlatformRunner-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - PlatformRunner
      - optparse-simple

    ghc-options:
      # - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  PlatformRunner-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - PlatformRunner
      - hspec

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
